### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by lxiange** [lxiange/CMS_for_SE_b#3]
有啥建议贴在这儿吧，任何方面 :P
大家伙儿积极点啊~

**Comment by xfge** [comment]
我没别的，来抢个沙发。

**Comment by micrazy** [comment]
bug report: NameError: name 'cookieName' is not defined

**Comment by lxiange** [comment]
@micrazy 能把完整的 stack trace 贴上来么？

**Comment by Toydi** [comment]
普通用户登录的时候，也能看到所有的成员信息，应该加个is_admin判断。

**Comment by lxiange** [comment]
@sheffieldge 注册界面没有include head.html，而是手写的，不够优雅，
以及，搞个统一的bottom.html吧，把底部的信息从main.html里拆分开来，这样也易于维护。
或许还有一些其他的TODO，你在代码里搜搜看吧。

**Comment by micrazy** [comment]
why this fucking css not appealing correctly on my computer

**Comment by xfge** [comment]
@Toydi is_admin只用于是否显示对成员的操作信息。

**Comment by micrazy** [comment]
bug report:
Traceback (most recent call last):
  File "D:\apps\Python34\lib\site-packages\tornado\web.py", line 1443, in _execute
    result = method(_self.path_args, *_self.path_kwargs)
  File "C:\Users\user\Desktop\CMS_for_SE_b-master\handlers.py", line 37, in get
    announcements=ad.fetch_all())
  File "C:\Users\user\Desktop\CMS_for_SE_b-master\dao.py", line 237, in fetch_all
    self.cur.execute("SELECT \* FROM announcement")
sqlite3.OperationalError: no such table: announcement

**Comment by Toydi** [comment]
点击注册有个Bug:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\tornado\web.py", line 1443, in _execute
    result = method(_self.path_args, *_self.path_kwargs)
  File "C:\Users\Toydi\Desktop\CMS_for_SE_b-master\handlers.py", line 94, in get
    self.render('register.html', same_name=False, cookie_name=username)
  File "C:\Python34\lib\site-packages\tornado\web.py", line 699, in render
    html = self.render_string(template_name, **kwargs)
  File "C:\Python34\lib\site-packages\tornado\web.py", line 806, in render_string
    return t.generate(**namespace)
  File "C:\Python34\lib\site-packages\tornado\template.py", line 345, in generate
    return execute()
  File "register_html.generated.py", line 116, in _tt_execute
    for msg in messages:  # main.html:142
NameError: name 'messages' is not defined

**Comment by lxiange** [comment]
@sheffieldge @micrazy @Toydi 
**Project complete!
Have a nice day!**
